[build]
  command = "npm run build -w=zd-286529-1"
  publish = "./packages/site-1/.next/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  force = true
  from = "/products"
  status = 200
  to = "https://zd-286529-2.netlify.app/legacy/products"

[[redirects]]
  force = true
  from = "/products/*"
  status = 200
  to = "https://zd-286529-2.netlify.app/legacy/products/:splat"

[[redirects]]
  force = true
  from = "/legacy/_next/*"
  status = 200
  to = "https://zd-286529-2.netlify.app/legacy/_next/:splat"